NAME          := eeka
VERSION       := 0.1

PREFIX        ?= /usr
DATA_DIR      := $(PREFIX)/share/$(NAME)
BUILD_DIR     ?= build

SHELL         := /bin/bash
.ONESHELL:
.DEFAULT_GOAL := all

SRC := $(wildcard src/*.c)
OBJ := $(patsubst src/%.c,$(BUILD_DIR)/%.o,$(SRC))

CPPFLAGS += -Wall -Wextra -std=c99 -D_GNU_SOURCE -O2 -I./src -I./$(BUILD_DIR)
LDFLAGS  += -lxcb -lxcb-keysyms -lxcb-xtest

run:
	$(MAKE) clean
	$(MAKE) $(BUILD_DIR)/$(NAME) --no-print-directory 2>&1 | tee -a .gcc
	./$(BUILD_DIR)/$(NAME) -c .config -V

$(BUILD_DIR)/config.h: GNUmakefile | $(BUILD_DIR)
	@echo "/* Generated by makefile */" > $@
	@echo "#define VERSION \"$(VERSION)\"" >> $@
	@echo "#define PROGRAM_NAME \"$(NAME)\"" >> $@
	@echo "#define DATA_DIR \"$(DATA_DIR)\"" >> $@

install: $(BUILD_DIR)/$(NAME)
	install -Dm 755 $^ "$(PREFIX)/bin/$(NAME)"
	install -Dm 633 data/config "$(DATA_DIR)/config"

uninstall:
	rm -f "$(PREFIX)/bin/$(NAME)" "$(DATA_DIR)/config"
	rmdir "$(DATA_DIR)"

$(BUILD_DIR)/%.o: src/%.c $(BUILD_DIR)/config.h | $(BUILD_DIR)
	gcc -c $< -o $@ $(CPPFLAGS)

$(BUILD_DIR)/$(NAME): $(OBJ)
	gcc $^ -o $@ $(LDFLAGS)

clean:
	rm -rf $(BUILD_DIR) .gcc

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

all: $(BUILD_DIR)/$(NAME)

.PHONY: all run clean install uninstall
